src/app/models.py
import uuid
from datetime import datetime
from time import time

import jwt
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from flask import current_app
from app import db, login


class User(UserMixin, db.Document):
    _id = db.StringField(primary_key=True, required=True) #mongodb autoimplemnt this field
    name = db.StringField(required=True)
    username = db.StringField(unique=True, required=True)
    password_hash = db.StringField(required=True)
    email = db.EmailField(unique=True, required=True)
    answered = db.BooleanField(default=False, required=True)
    # activated

    def set_id(self, _id):
        self._id = _id

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {"reset_password": self._id, "exp": time() + expires_in},
            current_app.config["SECRET_KEY"], algorithm="HS256").decode("utf-8")

    def get_answer(self):
        return self.answered

    def set_answer(self, value):
        self.answered = value

    @staticmethod
    def verify_reset_password_token(token):
        try:
            _id = jwt.decode(token, current_app.config["SECRET_KEY"],
                            algorithms=["HS256"])["reset_password"]
        except:
            return None
        return User.objects(_id=_id).first()

@login.user_loader
def load_user(_id):
    return User.objects(_id=_id).first()


class Answer(db.Document):
    _id = db.StringField(primary_key=True, required=True) #mongodb autoimplemnt this field
    answer_1 = db.BooleanField(required=True)
    answer_2 = db.BooleanField(required=True)
    answer_3 = db.BooleanField(required=True)
    answer_4 = db.BooleanField(required=True)
    answer_5 = db.BooleanField(required=True)
    answer_6 = db.BooleanField(required=True)
    answer_7 = db.BooleanField(required=True)
    answer_8 = db.BooleanField(required=True)
    answer_9 = db.BooleanField(required=True)
    answer_10 = db.BooleanField(required=True)
    answer_11 = db.BooleanField(required=True)
    user_id = db.StringField(unique=True, required=True)

    @staticmethod
    def get_all_answers():
        all_answers = {}
        for answer in Answer.objects:
            for i in range(1, 12):
                if not all_answers.get(i):
                    all_answers[i] = 0
                if answer["answer_"+str(i)] == True:
                    all_answers[i] += 1
        return all_answers

src/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SubmitField


class AnswersForm(FlaskForm):
    answer_1 = BooleanField("Campus não fornece RU (Restaurante Universitário)")
    answer_2 = BooleanField("Problemas psicológicos")
    answer_3 = BooleanField("Questões familiares (ex: algum familiar com problema de saúde, etc)")
    answer_4 = BooleanField("Problemas financeiros")
    answer_5 = BooleanField("Saudades de casa")
    answer_6 = BooleanField("Transporte (ex: movimentação na cidade, ir para faculdade, etc)")
    answer_7 = BooleanField("Infraestrutura da cidade (ex: internet, aluguel, etc)")
    answer_8 = BooleanField("Segurança (ex: não se sente seguro na faculdade ou nas redondezas da mesma)")
    answer_9 = BooleanField("Comprometimento com o curso (ex: não leva o mesmo a sério e com o tempo se cria uma bola de neve)")
    answer_10 = BooleanField("Insatisfação com o curso (ex: não está se sentindo pessoalmente realizado com o curso)")
    answer_11 = BooleanField("Não se adaptou as diferenças regionais")
    submit = SubmitField('Submeter Formulário')

src/app/__init__.py
import logging
import os
from logging.handlers import RotatingFileHandler, SMTPHandler

from config import Config
from flask import Flask
from flask_login import LoginManager
from flask_mail import Mail
from flask_mongoengine import MongoEngine

db = MongoEngine()
login = LoginManager()
login.login_view = "auth.login"
login.login_message = "Por favor, faça o login antes de acessar essa página!"
login.login_message_category = "danger"
mail = Mail()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    login.init_app(app)
    mail.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    # sent a message to admin email reporting a database error for example
    if not app.debug and not app.testing:
        if app.config["MAIL_SERVER"]:
            auth = None
            if app.config["MAIL_USERNAME"] or app.config["MAIL_PASSWORD"]:
                auth = (app.config["MAIL_USERNAME"], app.config["MAIL_PASSWORD"])
            secure = None
            if app.config["MAIL_USE_TLS"]:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config["MAIL_SERVER"], app.config["MAIL_PORT"]),
                fromaddr="no-reply@" + app.config["MAIL_SERVER"],
                toaddrs=app.config["ADMINS"], subject="Índice de Evasão - Falha no sistema!",
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)

        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/ind_evasao.log', maxBytes=10240,
                                        backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Projeto de Índice de Evasão')
    
    return app

src/app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

src/app/main/routes.py
import uuid

from app import db
from app.auth.email import send_password_reset_email
from app.auth.forms import LoginForm, RegisterForm
from app.main import bp
from app.main.forms import AnswersForm
from app.models import Answer
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required


@bp.route("/index")
@bp.route("/")
def index():
    answers_form = AnswersForm()
    register_form = RegisterForm()
    login_form = LoginForm()
    return render_template("main/index.html",
                           answers_form=answers_form,
                           register_form=register_form,
                           login_form=login_form)


@bp.route("/answers", methods=["GET","POST"])
@login_required
def answers():
    answers_form = AnswersForm()
    if answers_form.validate_on_submit():
        answers = Answer(
            _id=uuid.uuid4().hex,
            answer_1=answers_form.answer_1.data, 
            answer_2=answers_form.answer_2.data,
            answer_3=answers_form.answer_3.data,
            answer_4=answers_form.answer_4.data,
            answer_5=answers_form.answer_5.data,
            answer_6=answers_form.answer_6.data,
            answer_7=answers_form.answer_7.data,
            answer_8=answers_form.answer_8.data,
            answer_9=answers_form.answer_9.data,
            answer_10=answers_form.answer_10.data,
            answer_11=answers_form.answer_11.data,
            user_id=current_user._id
        )
        current_user.set_answer(True)
        current_user.save()
        answers.save()        
        flash('Respota salva com sucesso!', "success")
    return redirect(url_for('main.index'))

@bp.route("/about")
def about():
    return render_template("about.html")

src/app/templates/about.html
{% extends "base.html" %}

{% block title %}Sobre{% endblock %}

{% block content %}
    
    <div class="container card-container">
        <div class="row justify-content-center">
            <div class="col-md-12 card-style">
                <h2 class="text-center">Quem somos?</h2>
                            
                <img class="img-fluid img-small mx-auto d-block" src="{{ url_for('static', filename='img/PET.png') }}">                
                
                <p>O Programa de Educação Tutorial (PET) é um programa de comprovada excelência, o qual compromete-se fundamentalmente em aprimorar os cursos de graduação. Trabalha com quatro vertentes principais que são: Ensino, Cultura, Pesquisa e Extensão e forma cidadãos que aprendem durante três anos a trabalhar em equipe, a irradiar para os demais colegas o espírito de liderança e o compromisso com a geração de conhecimento para a solução dos mais diversos problemas. É o único programa institucional voltado para graduação que trabalha no formato de grupo interdisciplinar, ancorado em alunos e professores e que recebe avaliação institucional e não individual.</p>

                <p>As normas operacionais do PET estão estabelecidas no documento de Orientações Básicas do Programa, que define como objetivos principais: oferecer uma formação acadêmica de excelente nível, visando a formação de um profissional crítico e atuante; promover a integração da formação acadêmica com a futura atividade profissional, especialmente no caso da carreira universitária; estimular a melhoria do ensino de graduação formando jovens bilingües, versáteis, de iniciativa, de expressão oral e argumentação, capazes também de fazer contatos, administrar o tempo e as tarefas. Nas Orientações Básicas do PET estão também estabelecidas características que incluem: formação acadêmica ampla; atuação coletiva; interação contínua entre bolsistas e corpos docente e discente; implementação de ações voltadas para a comunidade; planejamento e execução de um programa com atividades diversificadas.</p>

                <p>Cada grupo PET conta com um conjunto de alunos bolsistas, um professor-tutor, vários professores colaboradores e, muitas vezes, conta ainda com alunos voluntários que ajudam nas atividades do grupo. A renovação dos bolsistas é feita anualmente por meio de processo seletivo rigoroso, quando da saída daqueles que concluem a graduação. </p>
            </div>
        </div>
    </div>

{% endblock %}

src/app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %} - Ind_Ev</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <!-- my styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    
    <!-- chartjs -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Chart.css') }}">

</head>
<body>

    {% include "components/navbar.html" %}

    {% include "components/header.html" %}

    <div class="container">
        {% block content %}
        {% endblock %}    
    </div>

    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- font awesome icons -->    
    <script src="https://kit.fontawesome.com/5870b5524d.js" crossorigin="anonymous"></script>   
    <!-- chartjs --> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js" integrity="sha512-hZf9Qhp3rlDJBvAKvmiG+goaaKRZA6LKUO35oK6EsM0/kjPK32Yw7URqrq3Q+Nvbbt8Usss+IekL7CRn83dYmw==" crossorigin="anonymous"></script>

    <script>
        var ctx = document.getElementById('myChart').getContext('2d');

        var x = $('#answers_values_x').data();
        var y = $('#answers_values_y').data();

        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: x['x'],
                datasets: [{
                    label: 'Número de Votos',
                    data: y["y"],
                    barPercentage: 0.5,
                    // barThickness: 6,
                    // maxBarThickness: 8,
                    // minBarLength: 2,                    
                    backgroundColor: [
                        'rgba(255, 50, 50, 1)',
                        'rgba(0, 255, 0, 1)',
                        'rgba(0, 0, 255, 1)',
                        'rgba(100, 255, 150, 1)',
                        'rgba(0, 191, 255, 1)',
                        'rgba(128, 0, 255, 1)',
                        'rgba(191, 255, 0, 1)',
                        'rgba(255, 128, 0, 1)',
                        'rgba(0, 255, 255, 1)',
                        'rgba(255, 0, 191, 1)',
                        'rgba(64, 0, 255, 1)',                                             
                        
                    ],
                    borderColor: [
                        'rgba(255, 0, 0, 1)',
                        'rgba(0, 255, 0, 1)',
                        'rgba(0, 0, 255, 1)',
                        'rgba(255, 128, 0, 1)',
                        'rgba(0, 191, 255, 1)',
                        'rgba(128, 0, 255, 1)',
                        'rgba(191, 255, 0, 1)',
                        'rgba(255, 128, 0, 1)',
                        'rgba(0, 255, 255, 1)',
                        'rgba(255, 0, 191, 1)',
                        'rgba(64, 0, 255, 1)',    
                    ],
                    borderWidth: 0.5
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
        </script>    

</body>
</html>

src/app/templates/components/header.html
<h1 class="text-center">Sistema de formulário do projeto <code>Ind_Ev</code></h1>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} text-center" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endwith %}

src/app/templates/components/navbar.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-light default-color">
    <span class="navbar-brand" href="#">Ind_Ev</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == url_for('main.index') %} active {% elif request.path == url_for('auth.login') %} active {% elif request.path == url_for('auth.register') %} active {% endif %}">
                <a class="nav-link" href=" {{ url_for('main.index') }}">Início
                    {% if request.path == url_for('main.index') %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>       

            <li class="nav-item {{ 'active' if request.path == url_for('main.about') else '' }}">
                <a class="nav-link" href=" {{ url_for('main.about') }}">Sobre
                    {% if request.path == url_for('main.about') %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>            

            <!-- <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">Dropdown
            </a>
            <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
            </li> -->
        </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>

        {% if not current_user.is_anonymous %}            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right dropdown-default"
                aria-labelledby="navbarDropdownMenuLink-333">
                <a class="dropdown-item" href=" {{ url_for('auth.logout') }}">Sair</a>
              </div>
            </li>
        {% endif %}           
      </ul>
    </div>
  </nav>
  <!--/.Navbar -->

src/app/templates/index.html
{% extends "base.html" %}

{% block title %}Início{% endblock %}

{% block content %}

    <div class="container card-container">
        {% if current_user.is_anonymous %}

            <div class="row justify-content-center">
                <div class="col-md-5 card-style">
                    {% include "auth/register.html" %}
                </div>
                <div class="col-md-1">
                </div>                
                <div class="col-md-5 card-style">
                    {% include "auth/login.html" %}
                </div>
            </div>

        {% else %}

            <div class="row justify-content-center mb-5">
                <div class="col-md-5 card-style">    
                    {% include "profile.html" %}
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-10 card-style">
                    {% include "answers.html" %}   
                </div>
            </div>
        
        {% endif %}
    </div>

{% endblock content %}

src/app/templates/main/answers.html
{% if not current_user.get_answer() %}
    <h2>Formulário de respostas</h2>
    <form action="{{ url_for('main.answers') }}" method="post" novalidate>
        {{ answers_form.hidden_tag() }}

        <div class="form-group form-check">
            {{ answers_form.answer_1(class="form-check-input") }}
            {{ answers_form.answer_1.label(class="form-check-label") }}
        </div>

        <div class="form-group form-check">
            {{ answers_form.answer_2(class="form-check-input") }}
            {{ answers_form.answer_2.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_3(class="form-check-input") }}
            {{ answers_form.answer_3.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_4(class="form-check-input") }}
            {{ answers_form.answer_4.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_5(class="form-check-input") }}
            {{ answers_form.answer_5.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_6(class="form-check-input") }}
            {{ answers_form.answer_6.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_7(class="form-check-input") }}
            {{ answers_form.answer_7.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_8(class="form-check-input") }}
            {{ answers_form.answer_8.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_9(class="form-check-input") }}
            {{ answers_form.answer_9.label(class="form-check-label") }}
        </div>
        
        <div class="form-group form-check">
            {{ answers_form.answer_10(class="form-check-input") }}
            {{ answers_form.answer_10.label(class="form-check-label") }}
        </div>

        <div class="form-group form-check">
            {{ answers_form.answer_11(class="form-check-input") }}
            {{ answers_form.answer_11.label(class="form-check-label") }}
        </div>    
        <div class="row justify-content-center">
            {{ answers_form.submit(class="btnSubmit") }}
        </div>
    </form>
{% else %}
    <h4 class="text-center">Dê uma olhadinha no que nossos usuários estão respondendo!</h4> <br>

    <p class="text-center" style="font-weight: 300;">Até o momento tivemos <span style="font-weight: bold;">{{ n_answers }}</span> respostas!</p>

    <meta id="answers_values_x" data-x="{{ answers_values[0] }}">
    <meta id="answers_values_y" data-y="{{ answers_values[1] }}">

    <canvas id="myChart" class="img-fluid" alt="Answers"></canvas>    

    <div class="row justify-content-center">
        <div class="container-md6">
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-small">1. {{ answers_form.answer_1.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">2. {{ answers_form.answer_2.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">3. {{ answers_form.answer_3.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">4. {{ answers_form.answer_4.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">5. {{ answers_form.answer_5.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">6. {{ answers_form.answer_6.label(class="form-check-label") }}</li>
            </ul>
        </div>
        <div class="container-md6">
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-small">7. {{ answers_form.answer_7.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">8. {{ answers_form.answer_8.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">9. {{ answers_form.answer_9.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">10. {{ answers_form.answer_10.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small">11. {{ answers_form.answer_11.label(class="form-check-label") }}</li>
                <li class="list-group-item text-small"></li>
            </ul>
        </div>    
    </div>
{% endif %}

src/app/templates/main/index.html
{% extends "base.html" %}

{% block title %}Início{% endblock %}

{% block content %}

    <div class="container card-container">
        {% if current_user.is_anonymous %}

            <div class="row justify-content-center">
                <div class="col-md-5 card-style">
                    {% include "auth/register.html" %}
                </div>
                <div class="col-md-1">
                </div>                
                <div class="col-md-5 card-style">
                    {% include "auth/login.html" %}
                </div>
            </div>

        {% else %}

            <div class="row justify-content-center mb-5">
                <div class="col-md-5 card-style">    
                    {% include "profile.html" %}
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-10 card-style">
                    {% include "main/answers.html" %}   
                </div>
            </div>
        
        {% endif %}
    </div>

{% endblock content %}

src/app/templates/profile.html
<h4 class="text-center">Olá {{ current_user.name }}!</h4>
<br>
{% if current_user.get_answer() %}
    <p>Muito obrigado por responder nosso formulário!</p>
{% else %}
    <p style="white-space: nowrap;">Fique à vontade para responder nosso formulário!</p>
{% endif %}